name: Package and release

on:
  push:
    tags:
      - '**'

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow for your own token, the name cannot start with "GITHUB_"

    steps:

      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Package and release
        uses: BigWigsMods/packager@v1

      # - name: Package and release for Burning Crusade Classic
      #   uses: BigWigsMods/packager@v1
      #   with:
      #     args: -g bcc -w 0
